### ISSUE TITLE
Text disappears from title page after upgrade to 2.x

### ISSUE THREAD

**Issue by timtebeek** [asciidoctor/asciidoctorj-pdf#74]
When I switch from `1.6.2` to `2.0.6` my PDF title page no longer shows the document title.

Not really sure how much detail to include, but we are creating PDFs with a custom theme; here's the start of the asciidoc:

```
:doctype: book
:pdf-theme: acme-book
:source-highlighter: coderay
:listing-caption: Listing
ifndef::imagesdir[:imagesdir: images]
:back-cover-image: image:../themes/acme-cover-achterkant.svg[]

:author: Wile E. Coyote et al.
:lang: en
:orgname: acme
:keywords: keyword1, keyword2

= ACME Something something: With more details on the next line
```

That last line does show up when using 1.6.2, but disappears when we use 2.0.6.

Specifically in our theme we're using:
```
title-page:
  align: right
  background-image: acme-cover-voorkant.svg
  title:
    margin-top: -316
    margin-left: 70
    margin-right: -5
    font:
      family: GT-Walsheim
      color: #02B4E0
      size: 40
      style: bold
  subtitle:
    font:
      family: GT-Walsheim
      color: #000000
      size: 14
      style: bold_italic
    margin-top: 15
    margin-left: 100
    margin-right: -5
  revision:
    display: none
  authors:
    display: none
```
Any help or pointers appreciated, as I'm not seeing anything relevant in the logs either.
